from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

def convert2int(image):
    """ Transfrom from float tensor ([-1.,1.]) to int image ([0,255])
    """
    return tf.image.convert_image_dtype((image+1.0) * 0.5, tf.uint8)
    # return tf.image.convert_image_dtype(image, dtype=tf.uint8)

def batch_convert2int(images):
    return tf.map_fn(convert2int, images, dtype=tf.uint8)

class BaseGAN(object):

    def __init__(self, config):
        """Base GAN class, defines common props and methods to be subclassed
        Args:
            config: Object or hparams with model configurations
        Properties:
            optimizers: dict of Tensors
            losses: dict of Tensors
            outputs: dict of Tensors
        """
        self.build_model(config)
        self.optimizers = None
        self.losses = None
        self.outputs = None

    def build_model(self, config):
        raise NotImplementedError()

    def model(self, inputs):
        """GAN model function
        Args:
            inputs: tensor or list of tensors
                e.g. images, z_noise
        Returns:
            losses: dict of model loss tensors
            outputs: dict of output tensors
            optimizers: dict of optimizers
        """
        raise NotImplementedError()
    
    def eval(self, inputs):
        """Eval mode model function
        Args:
            inputs: tensor or list of tensors
                e.g. z_noise
        Returns:
            outputs: Tensor of fake images generated by G(z), 
            has shape [b, h, w, c]
        """
        raise NotImplementedError()    