from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
from tensor2gan.models.base import batch_convert2int
from tensor2gan.models.base import BaseGAN
from tensor2gan.utils import registry

@registry.register_model
class DCGAN(BaseGAN):
    """
    DCGAN model

    "Unsupervised Representation Learning with Deep Convolutional Generative Adversarial Networks"
    https://arxiv.org/abs/1511.06434
    
    configs:
        input_shape: tuple or list for Discriminator input shape (or Generator output shape)
        gen_filters: int, Generator top layer filters
        dis_filters: int, Discriminator top layer filters
        label_smoothing: float, applied to d_loss_fake label smoothing
        clip_gradients: float, applied to D and G gradients
        learning_rate: float, Adam optimizer learning rate
        beta1: float, Adam optimizer momentum
    """
    def build_model(self, config):
        # params
        input_shape = config.input_shape
        g_filters = config.gen_filters
        d_filters = config.dis_filters

        self.config = config

        self.G = Generator(output_shape=input_shape, filters=g_filters)
        self.D = Discriminator(filters=d_filters)

    def model(self, inputs):
        """Model function for training
        Args:
            inputs: [real_data_batch, z_noise] Tensors 
        Returns:
            losses: dict, {d_loss_real, d_loss_fake, g_loss}
            outputs: dict, {d_real, d_fake, fake_data}
            optimizers: dict, {d_optim, g_optim}
        """
        real_data, z = inputs

        # outputs
        fake_data = self.G(z)
        d_real, d_real_logits = self.D(real_data)
        d_fake, d_fake_logits = self.D(fake_data)
        self.outputs = dict(
            fake_data=fake_data, 
            d_real=d_real, 
            d_fake=d_fake
        )
        for key, val in self.outputs.items():
            tf.summary.histogram(key, val)
        
        # losses
        if self.config.label_smoothing is not None:
            d_loss_real, d_loss_fake, g_loss = label_smoothing_losses(
                d_real_logits, d_fake_logits, self.config.label_smoothing)
        else:
            d_loss_real, d_loss_fake, g_loss = get_losses(d_real_logits, d_fake_logits)

        d_loss = d_loss_real + d_loss_fake
        self.losses = dict(
            d_loss_real=d_loss_real, 
            d_loss_fake=d_loss_fake, 
            d_loss=d_loss,
            g_loss=g_loss
        )
        for key, val in self.losses.items():
            tf.summary.scalar(key, val)

        # training ops / optimize step
        lr = self.config.learning_rate
        beta1 = self.config.beta1
        clip_gradients = self.config.clip_gradients

        with tf.control_dependencies(tf.get_collection(tf.GraphKeys.UPDATE_OPS)):
            d_optim = create_optimizer(d_loss, self.D.variables, 
                lr=lr * 0.5, beta1=beta1, clip_gradients=clip_gradients)

        # train D then G
        with tf.control_dependencies([d_optim]):
            g_optim = create_optimizer(g_loss, self.G.variables, 
                lr=lr, beta1=beta1, clip_gradients=clip_gradients)

        # group training ops
        self.optimizers = tf.group(d_optim, g_optim)
        
        return self.losses, self.outputs, self.optimizers
        
    def eval(self, inputs, add_summaries=True):
        """Generator output for given noise tensor Z. 
        Args:
            inputs: list of tensors [real_data, noise] where:
                real_data: tensor of images with shape [batch, height, width, channel]
                noise: noise tensor with shape [batch, z_dim]
        Returns:
            outputs: Tensor of fake images generated by G(z), 
            has shape [b, h, w, c]
        """
        real_data, noise = inputs
        fake_data = self.G(noise, training=False)
        if add_summaries:
            tf.summary.image("eval/real_data", batch_convert2int(real_data), collections="EVAL_SUMMARIES")
            tf.summary.image("eval/fake_data", batch_convert2int(fake_data), collections="EVAL_SUMMARIES")
        return fake_data


def create_optimizer(loss, var_list, lr=1e-3, beta1=0.5, clip_gradients=None):
    """Create optimizer with gradient clipping. Returns training op. 
    """
    optimizer = tf.train.AdamOptimizer(lr, beta1=beta1)
    gradients, variables = zip(*optimizer.compute_gradients(loss, var_list=var_list))
    if clip_gradients:
        gradients, _ = tf.clip_by_global_norm(gradients, clip_gradients)
    op = optimizer.apply_gradients(zip(gradients, variables),
        global_step=tf.train.get_or_create_global_step())
    return op

def label_smoothing_losses(d_real_logits, d_fake_logits, label_smoothing=0.9):
    """Returns DCGAN losses with label smoothing. 

    We flip discriminator labels:
    D(real) = 0, D(fake) = 1
    We use label smoothing on D(fake) e.g. 0.9

    Args:
        d_real_logits: tensor of logit D(real_data)
        d_fake_logits: tensor of logit D(fake_data)
    Returns:
        d_loss_real: loss tensor for D(real)
        d_loss_fake: loss tensor for D(fake)
        g_loss: loss tensor for G(z)
    """
    d_loss_real = tf.reduce_mean(
        tf.nn.sigmoid_cross_entropy_with_logits(
            logits=d_real_logits, labels=tf.zeros_like(d_real_logits))
    )
    d_loss_fake = tf.reduce_mean(
        tf.nn.sigmoid_cross_entropy_with_logits(
            logits=d_fake_logits, labels=label_smoothing * tf.ones_like(d_fake_logits))
    )
    g_loss = tf.reduce_mean(
        tf.nn.sigmoid_cross_entropy_with_logits(
            logits=d_fake_logits, labels=tf.zeros_like(d_fake_logits))
    )
    return d_loss_real, d_loss_fake, g_loss

def get_losses(d_real_logits, d_fake_logits):
    """Returns DCGAN losses
    Args:
        d_real_logits: tensor of logit D(real_data)
        d_fake_logits: tensor of logit D(fake_data)
    Returns:
        d_loss_real: loss tensor for D(real)
        d_loss_fake: loss tensor for D(fake)
        g_loss: loss tensor for G(z)
    """
    d_loss_real = tf.reduce_mean(
        tf.nn.sigmoid_cross_entropy_with_logits(
            logits=d_real_logits, labels=tf.ones_like(d_real_logits))
    )
    d_loss_fake = tf.reduce_mean(
        tf.nn.sigmoid_cross_entropy_with_logits(
            logits=d_fake_logits, labels=tf.zeros_like(d_fake_logits))
    )
    g_loss = tf.reduce_mean(
        tf.nn.sigmoid_cross_entropy_with_logits(
            logits=d_fake_logits, labels=tf.ones_like(d_fake_logits))
    )
    return d_loss_real, d_loss_fake, g_loss

class Generator:
    
    def __init__(self, name="G", filters=1024, output_shape=(32, 32, 3)):
        self.name = name
        self.filters = filters
        self.output_shape = output_shape
        self.reuse = False

    def __call__(self, z, training=True):
        """
        Args:
            z: noise tensor [None, z_dim]
        Returns:
            output: tensor with shape = self.output_shape
        """
        # output shapes: h/16, h/8, h/4, h/2, h
        h, w, c = self.output_shape
        h0, w0 = int(h/16), int(w/16)   # 2, 2
        
        # filters: 1024, 512, 256, 128, c
        f0, f1, f2, f3, f4 = self.filters, int(self.filters/2), int(self.filters/4), int(self.filters/8), c

        def linear_projection(z):
            # linear projection of z
            with tf.variable_scope("linear", reuse=self.reuse):
                g = tf.layers.dense(z, units=h0*w0*f0)
                g = tf.reshape(g, shape=[-1, h0, w0, f0])
                g = tf.layers.batch_normalization(g, training=training)
                g = tf.nn.leaky_relu(g, alpha=0.2)
                return g
                
        def deconv_block(x, filters, kernel_size=[4,4], strides=(2,2), padding='SAME'):
            with tf.variable_scope("deconv%d" % filters, reuse=self.reuse):
                g = tf.layers.conv2d_transpose(x, filters, kernel_size, strides=strides, padding=padding,
                    kernel_initializer=tf.truncated_normal_initializer(stddev=0.02))
                g = tf.layers.batch_normalization(g, training=training)
                g = tf.nn.leaky_relu(g, alpha=0.2)
                return g

        def last_deconv_block(x, filters, kernel_size=[4,4], strides=(2,2), padding='SAME'):
            with tf.variable_scope("deconv%d" % filters, reuse=self.reuse):
                g = tf.layers.conv2d_transpose(x, filters, kernel_size, strides=strides, padding=padding,
                    kernel_initializer=tf.truncated_normal_initializer(stddev=0.02))
                g = tf.nn.tanh(g)
                return g
            
        # model
        with tf.variable_scope(self.name, reuse=self.reuse):
            z = tf.reshape(z, [z.get_shape()[0], 1, 1, -1])
            g = deconv_block(z, f0, strides=(1,1), padding='VALID') # 1024, 2x2
            g = deconv_block(g, f1) # 512, 4x4
            g = deconv_block(g, f2) # 256, 8x8
            g = deconv_block(g, f3) # 128, 16x16
            output = last_deconv_block(g, f4) # 3, 32x32, tanh

        self.reuse = True
        self.variables = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, scope=self.name)
        return output

class Discriminator:
    
    def __init__(self, name="D", filters=64):
        self.name = name
        self.filters = filters
        self.reuse = False

    def __call__(self, inputs, training=True):
        """
        Args:
            inputs: image tensor [batch, w, h, c]
        Returns:
            output: Tensor
            logit: Tensor, sigmoid logit
        """
        # filters: 64, 128, 256, 512
        f0, f1, f2, f3 = self.filters, self.filters*2, self.filters*4, self.filters*8
                    
        def conv_block(x, filters):
            with tf.variable_scope("conv%d" % filters, reuse=self.reuse):
                d = tf.layers.conv2d(x, filters, [5,5], strides=(2,2), padding='SAME',
                    kernel_initializer=tf.truncated_normal_initializer(stddev=0.02))
                d = tf.layers.batch_normalization(d, training=training)
                d = tf.nn.leaky_relu(d, alpha=0.2)
                return d
        
        def dense_block(x, filters=1024):
            with tf.variable_scope("dense", reuse=self.reuse):
                d = tf.layers.dense(x, filters)
                d = tf.layers.batch_normalization(d, training=training)
                d = tf.nn.leaky_relu(d, alpha=0.2)
                return d

        # model
        with tf.variable_scope(self.name, reuse=self.reuse):
            d = conv_block(inputs, f0)
            d = conv_block(d, f1)
            d = conv_block(d, f2)
            d = conv_block(d, f3)
            d = dense_block(d, 1024)
            logit = tf.layers.dense(d, 1) 
            output = tf.nn.sigmoid(logit) # prob(y|x)

        self.reuse = True
        self.variables = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, scope=self.name)
        return output, logit